# Generated by Django 5.2.6 on 2025-09-28 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Record",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=150, verbose_name="Заголовок")),
                ("contents", models.CharField(max_length=150, verbose_name="Содержимое")),
                ("image", models.ImageField(blank=True, null=True, upload_to="images/", verbose_name="Изображение")),
                ("is_publication", models.BooleanField(default=True)),
                ("number_of_views", models.IntegerField()),
                ("created_at", models.DateField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "запись",
                "verbose_name_plural": "записи",
                "ordering": ["title", "contents"],
            },
        ),
    ]
