# Generated by Django 5.2.6 on 2025-09-30 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myblog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="record",
            name="contents",
            field=models.TextField(verbose_name="Содержимое"),
        ),
    ]
