# Generated by Django 5.2.6 on 2025-09-30 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myblog", "0002_alter_record_contents"),
    ]

    operations = [
        migrations.AlterField(
            model_name="record",
            name="number_of_views",
            field=models.PositiveIntegerField(),
        ),
    ]
